### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [tromey/emacs-status#1]
If i'm not wrong, your package is an utility to be able to add status to emacs icon.

How should it be installed?

Tell me if you interested that I add the melpa recipe so that `status` is just a `package-install`away :)

**Comment by tromey** [comment]
What I did is `make`, then in Emacs use `package-install-file` to install the resulting tar file.

I am not a big fan of MELPA's approach.  I could put it on marmalade if you want.  Or maybe we could work out how to get it on melpa-stable.

**Comment by AdrieanKhisbe** [comment]
melpa stable for the win :)

**Comment by purcell** [comment]
Just add a numeric version tag to the repo for it to end up on MELPA Stable.

**Comment by tromey** [comment]
I pushed the "0.3" tag.

**Comment by AdrieanKhisbe** [comment]
:+1: great :)
